name: Generate Snake

on:
  # This trigger allows manual triggering of the workflow from the Actions tab
  workflow_dispatch:  

  # This trigger runs the workflow every 6 hours based on the cron schedule
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate the snake contribution graph
      - uses: Platane/snk@v2
        with:
          github_user_name: saurabhchaudhary05
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.8.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
